name: 'rocket-rust-boilerplate'
version: '3.1'
services:
  database:
    container_name: rocket-rust-boilerplate-database
    image: postgres
    environment:
      TZ: Asia/Jakarta
      POSTGRES_DB: boilerplate
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
  backend:
    container_name: rocket-rust-boilerplate-backend
    build: 
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      TZ: Asia/Jakarta
      DATABASE_URL: postgres://root:root@host.docker.internal/boilerplate
    command: cargo watch -x "run --release"
    ports:
      - 8000:8000
    volumes:
      - ./migrations:/app/migrations
      - ./src:/app/src
      - ./.env:/app/.env
      - ./Cargo.toml:/app/Cargo.toml
      - ./Rocket.toml:/app/Rocket.toml