CREATE TABLE role_user (
  id VARCHAR(36) PRIMARY KEY NOT NULL,
  role_id VARCHAR(36) NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE role_user ADD FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE;
ALTER TABLE role_user ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
